function A = COMSOLdataread(fname)
%   A = COMSOLdataread(fname) reads the data in the txt file generated by
%   COMSOL
%   == Input ==
%   fname : name of the txt file
%   == Output ==
%   A : the data matrix


fid = fopen(fname,'r');

% Get rid of the header
pos = ftell(fid);
l = fgetl(fid);
while l(1) == '%'
    pos = ftell(fid);
    l = fgetl(fid);
end

fseek(fid,pos,'bof');
sizeA = [length(str2num(fgetl(fid))) inf];
fseek(fid,pos,'bof');
formatSpec = repmat('%f ',1,sizeA(1));
A = fscanf(fid,formatSpec,sizeA);
fclose(fid);
end